[Settings]
# --- Основные параметры для анализа ---

# Введите кадастровый номер целевого участка
kad_id = 86:14:0101002:715

# Укажите радиус поиска соседних участков в метрах
radius_meters = 200

# --- Дополнительные параметры ---

# Рисовать ли график с картой участков?
# Возможные значения: true / false (или yes / no)
draw_plot = yes

# Лимит по площади для ЗУ
area_limit = 50